{% set name = "aiohttp-client-cache" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp_client_cache-{{ version }}.tar.gz
  sha256: b9ad0345bbb08306a8b2b4d60bdbc8f87759bed2a90c7de4aea5c0773cad63d3

build:
  script: python -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - aiohttp >=3.8
    - aiosqlite >=0.16
    - attrs >=21.2
    - itsdangerous >=2.0
    - url-normalize >=1.4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - aiohttp_client_cache
    - aiohttp_client_cache.backends

about:
  home: https://github.com/requests-cache/aiohttp-client-cache
  summary: Persistent cache for aiohttp requests
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/requests-cache/aiohttp-client-cache
  doc_url: https://aiohttp-client-cache.readthedocs.io

extra:
  recipe-maintainers:
    - JWCook
    - cheginit
