{% set name = "aiohttp-client-cache" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiohttp_client_cache-{{ version }}.tar.gz
  sha256: af5556f719814aca02db6384271069cec6a67be31a6b7d9437e0a6a9980a494f

build:
  script: python -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - aiohttp >=3.8
    - aiosqlite >=0.16
    - attrs >=21.2
    - itsdangerous >=2.0
    - url-normalize >=2.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - aiohttp_client_cache
    - aiohttp_client_cache.backends

about:
  home: https://github.com/requests-cache/aiohttp-client-cache
  summary: Persistent cache for aiohttp requests
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/requests-cache/aiohttp-client-cache
  doc_url: https://aiohttp-client-cache.readthedocs.io

extra:
  recipe-maintainers:
    - JWCook
    - cheginit
